jQuery('.test')
    .addClass('red')
    .find('div')
    .addClass('green')
    .addClass('blue')
    .addClass('pink')
    .end()
    .addClass('hello')
    // .each(x => console.log(x))
    // .end()
    // .parent().print()
    .children().print()